name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run test script
        run: |
          python test.py
          mv results.txt ${{ matrix.python-version }}-results.txt
          git config user.name  github-action
          git config user.email github-actions@github.com
          git add ${{ matrix.python-version }}-results.txt
          git commit -m "chore: results."
          git push
